#include "InternalEvents.h"

DEFINE_LOCAL_EVENT_TYPE ( wxEVT_CORE_FILE_HASHING_FINISHED )
DEFINE_LOCAL_EVENT_TYPE ( wxEVT_CORE_FILE_HASHING_SHUTDOWN )
DEFINE_LOCAL_EVENT_TYPE ( wxEVT_CORE_FINISHED_FILE_COMPLETION )
DEFINE_LOCAL_EVENT_TYPE ( wxEVT_CORE_FINISHED_HTTP_DOWNLOAD )
DEFINE_LOCAL_EVENT_TYPE ( wxEVT_CORE_SOURCE_DNS_DONE )
DEFINE_LOCAL_EVENT_TYPE ( wxEVT_CORE_UDP_DNS_DONE )
DEFINE_LOCAL_EVENT_TYPE ( wxEVT_CORE_SERVER_DNS_DONE )
